# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0002_guide_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='editDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
