# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0003_auto_20160502_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='guides',
        ),
        migrations.AlterField(
            model_name='entry',
            name='waterLevel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
