# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0003_entry_river'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='trip_type',
            field=models.CharField(choices=[(('KYK',), 'Kayak'), ('RFT', 'Raft')], max_length=3, null=True),
        ),
    ]
