# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0004_auto_20160502_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='tripLeader',
            field=models.BooleanField(default=False, verbose_name='Are you the trip leader?'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='river',
            field=models.CharField(choices=[('White Salmon Half-Day', 'White Salmon Half-Day'), ('White Salmon Full-Day', 'White Salmon Full-Day'), ('Wind River', 'Wind River'), ('Klickitat River', 'Klickitat River'), ('Hood River', 'Hood River'), ('The Farmlands', 'The Farmlands'), ('Tieton River', 'Tieton River'), ('Kayak Course', 'Kayak Course')], max_length=64, null=True),
        ),
    ]
