# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0005_entry_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='leader',
        ),
    ]
