# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0005_auto_20160509_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='trip_type',
        ),
    ]
