# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0007_entry_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='leader',
            field=models.BooleanField(default=False),
        ),
    ]
