# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0009_auto_20160407_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='kayaks',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='rafts',
            field=models.IntegerField(null=True),
        ),
    ]
