# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0010_auto_20160407_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='employee',
            new_name='guide',
        ),
    ]
