# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0011_auto_20160407_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guide',
            old_name='name',
            new_name='FirstName',
        ),
        migrations.AddField(
            model_name='guide',
            name='LastName',
            field=models.CharField(default='blank', max_length=64),
            preserve_default=False,
        ),
    ]
