# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0012_auto_20160407_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='kayaks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='rafts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
