# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0013_auto_20160407_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='general_description',
            field=models.TextField(blank=True, max_length=356, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='guest_problems',
            field=models.TextField(blank=True, max_length=356, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='problems',
            field=models.TextField(blank=True, max_length=356, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='trip_type',
            field=models.CharField(choices=[('KYK', 'Kayak'), ('RFT', 'Raft')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='weather',
            field=models.TextField(blank=True, max_length=356, null=True),
        ),
    ]
