# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0014_auto_20160407_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='river',
            field=models.CharField(choices=[('White Salmon Half-Day', 'White Salmon Half-Day'), ('White Salmon Full-Day', 'White Salmon Full-Day'), ('Wind River', 'Wind River'), ('Klickitat River', 'Klickitat River'), ('Hood River', 'Hood River'), ('The Farmlands', 'The Farmlands'), ('Tieton River', 'Tieton River')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='trip_type',
            field=models.CharField(choices=[('Kayak', 'Kayak'), ('Raft', 'Raft')], max_length=64, null=True),
        ),
    ]
