# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0015_auto_20160407_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader', related_query_name='leader', to='triplog.Guide'),
        ),
    ]
