# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0016_auto_20160407_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='guides',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guides', related_query_name='guides', to='triplog.Guide'),
        ),
    ]
