# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20160411_1618'),
        ('triplog', '0017_entry_guides'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('organizations.organization',),
        ),
        migrations.CreateModel(
            name='AccountUser',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('organizations.organizationuser',),
        ),
    ]
